### PR TITLE
DEP Allow graphql ^6

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/191

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
We probably need to decide how we want to handle this one - maintaining it will be easier if we don't do multi-branch support like this.

**Comment by emteknetnz** [comment]
Why would it be easier?  This PR seems easier.

**Comment by GuySartorelli** [comment]
Any breaking changes in other graphql 6 may cause problems with this. It's the same reason we bump other modules like config which may not directly need it.

**Comment by emteknetnz** [comment]
I'd say that's graphql 6 is very unlikely to break this. There hasn't been any discussion for work on GraphQL 6 so most likely scenarios is that it will be near identical to GraphQL 5

If we do run into problems at a future then we can access whether we should adapt the `1` branch of this module to add support for GraphQL 6, or if we should create a new `2` branch instead

**Review by GuySartorelli — APPROVED** [review]
Seems weird that we're handling this one differently than everything else, when the argument was that we should just handle everything the same way... but w/e.

**Pull request merged**
